window.hadithDatabase = [
    { text: "إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى...", book: "صحيح البخاري", grade: "صحيح", narrator: "عمر بن الخطاب", bookKey: "bukhari", scholar: "البخاري" },
    { text: "من سلك طريقاً يلتمس فيه علماً سهل الله له به طريقاً إلى الجنة", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "الدين النصيحة، قلنا: لمن؟ قال: لله ولكتابه ولرسوله ولأئمة المسلمين وعامتهم", book: "صحيح مسلم", grade: "صحيح", narrator: "تميم الداري", bookKey: "muslim", scholar: "مسلم" },
    { text: "كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن: سبحان الله وبحمده، سبحان الله العظيم", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "الطهور شطر الإيمان والحمد لله تملأ الميزان...", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو مالك الأشعري", bookKey: "muslim", scholar: "مسلم" },
    { text: "اتق الله حيثما كنت، وأتبع السيئة الحسنة تمحها، وخالق الناس بخلق حسن", book: "جامع الترمذي", grade: "حسن صحيح", narrator: "أبو ذر الغفاري", bookKey: "tirmidhi", scholar: "الترمذي" },
    { text: "احفظ الله يحفظك، احفظ الله تجده تجاهك...", book: "جامع الترمذي", grade: "حسن صحيح", narrator: "ابن عباس", bookKey: "tirmidhi", scholar: "الترمذي" },
    { text: "لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه", book: "صحيح البخاري", grade: "صحيح", narrator: "أنس بن مالك", bookKey: "bukhari", scholar: "البخاري" },
    { text: "بني الإسلام على خمس: شهادة أن لا إله إلا الله...", book: "صحيح البخاري", grade: "صحيح", narrator: "ابن عمر", bookKey: "bukhari", scholar: "البخاري" },
    { text: "دع ما يريبك إلى ما لا يريبك، فإن الصدق طمأنينة والكذب ريبة", book: "جامع الترمذي", grade: "صحيح", narrator: "الحسن بن علي", bookKey: "tirmidhi", scholar: "الترمذي" },
    { text: "من حسن إسلام المرء تركه ما لا يعنيه", book: "جامع الترمذي", grade: "حسن", narrator: "أبو هريرة", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "لا تحاسدوا، ولا تناجشوا، ولا تباغضوا، ولا تدابروا...", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "كل سلامى من الناس عليه صدقة كل يوم تطلع فيه الشمس...", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "البر حسن الخلق، والإثم ما حاك في صدرك وكرهت أن يطلع عليه الناس", book: "صحيح مسلم", grade: "صحيح", narrator: "النواس بن سمعان", bookKey: "muslim", scholar: "مسلم" },
    { text: "إن الله لا ينظر إلى أجسادكم ولا إلى صوركم ولكن ينظر إلى قلوبكم وأعمالكم", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "خيركم من تعلم القرآن وعلمه", book: "صحيح البخاري", grade: "صحيح", narrator: "عثمان بن عفان", bookKey: "bukhari", scholar: "البخاري" },
    { text: "عجباً لأمر المؤمن إن أمره كله خير، وليس ذاك لأحد إلا للمؤمن...", book: "صحيح مسلم", grade: "صحيح", narrator: "صهيب الرومي", bookKey: "muslim", scholar: "مسلم" },
    { text: "من يرد الله به خيراً يفقهه في الدين", book: "صحيح البخاري", grade: "صحيح", narrator: "معاوية بن أبي سفيان", bookKey: "bukhari", scholar: "البخاري" },
    { text: "تبسمك في وجه أخيك صدقة", book: "جامع الترمذي", grade: "صحيح", narrator: "أبو ذر الغفاري", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "الراحمون يرحمهم الرحمن، ارحموا من في الأرض يرحمكم من في السماء", book: "سنن أبي داود", grade: "صحيح", narrator: "عبد الله بن عمرو", bookKey: "abudawud", scholar: "الألباني" },
    { text: "من كان يؤمن بالله واليوم الآخر فليقل خيراً أو ليصمت", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "إن الله جميل يحب الجمال، الكبر بطر الحق وغمط الناس", book: "صحيح مسلم", grade: "صحيح", narrator: "عبد الله بن مسعود", bookKey: "muslim", scholar: "مسلم" },
    { text: "أحب الأعمال إلى الله أدومها وإن قل", book: "صحيح البخاري", grade: "صحيح", narrator: "عائشة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "إن الله يحب إذا عمل أحدكم عملاً أن يتقنه", book: "المعجم الأوسط", grade: "حسن", narrator: "عائشة", bookKey: "other", scholar: "الألباني" },
    { text: "الدنيا سجن المؤمن وجنة الكافر", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "المسلم من سلم المسلمون من لسانه ويده", book: "صحيح البخاري", grade: "صحيح", narrator: "عبد الله بن عمرو", bookKey: "bukhari", scholar: "البخاري" },
    { text: "المؤمن للمؤمن كالبنيان يشد بعضه بعضاً", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو موسى الأشعري", bookKey: "bukhari", scholar: "البخاري" },
    { text: "إن مما أدرك الناس من كلام النبوة الأولى: إذا لم تستح فاصنع ما شئت", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو مسعود عقبة بن عمرو", bookKey: "bukhari", scholar: "البخاري" },
    { text: "من صام رمضان إيماناً واحتساباً غفر له ما تقدم من ذنبه", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "اجعلوا من صلاتكم في بيوتكم ولا تتخذوها قبوراً", book: "صحيح البخاري", grade: "صحيح", narrator: "ابن عمر", bookKey: "bukhari", scholar: "البخاري" },
    { text: "خير الناس أنفعهم للناس", book: "المعجم الأوسط", grade: "حسن", narrator: "جابر بن عبد الله", bookKey: "other", scholar: "الألباني" },
    { text: "إن الله رفيق يحب الرفق في الأمر كله", book: "صحيح البخاري", grade: "صحيح", narrator: "عائشة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "الصدق يهدي إلى البر، وإن البر يهدي إلى الجنة...", book: "صحيح البخاري", grade: "صحيح", narrator: "ابن مسعود", bookKey: "bukhari", scholar: "البخاري" },
    { text: "لا ضرر ولا ضرار", book: "سنن ابن ماجه", grade: "صحيح", narrator: "ابن عباس", bookKey: "ibnmajah", scholar: "الألباني" },
    { text: "إن الله لا يقبض العلم انتزاعاً ينتزعه من العباد، ولكن يقبض العلم بقبض العلماء", book: "صحيح البخاري", grade: "صحيح", narrator: "عبد الله بن عمرو", bookKey: "bukhari", scholar: "البخاري" },
    { text: "إذا مات ابن آدم انقطع عمله إلا من ثلاث: صدقة جارية، أو علم ينتفع به، أو ولد صالح يدعو له", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "ما نقص مال من صدقة، وما زاد الله عبدا بعفو إلا عزا", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "من أصبح منكم آمناً في سربه، معافى في جسده، عنده قوت يومه، فكأنما حيزت له الدنيا", book: "جامع الترمذي", grade: "حسن", narrator: "عبيد الله بن محصن", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "أكثروا ذكر هاذم اللذات: الموت", book: "جامع الترمذي", grade: "حسن صحيح", narrator: "أبو هريرة", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "طلب العلم فريضة على كل مسلم", book: "سنن ابن ماجه", grade: "حسن", narrator: "أنس بن مالك", bookKey: "ibnmajah", scholar: "الألباني" },
    { text: "الدال على الخير كفاعله", book: "جامع الترمذي", grade: "صحيح", narrator: "أنس بن مالك", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "لا يدخل الجنة من كان في قلبه مثقال ذرة من كبر", book: "صحيح مسلم", grade: "صحيح", narrator: "ابن مسعود", bookKey: "muslim", scholar: "مسلم" },
    { text: "إن الحلال بين وإن الحرام بين، وبينهما مشتبهات لا يعلمهن كثير من الناس...", book: "صحيح البخاري", grade: "صحيح", narrator: "النعمان بن بشير", bookKey: "bukhari", scholar: "البخاري" },
    { text: "ليس الشديد بالصُّرَعة، إنما الشديد الذي يملك نفسه عند الغضب", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "إنما الأعمال بالخواتيم", book: "صحيح البخاري", grade: "صحيح", narrator: "سهل بن سعد", bookKey: "bukhari", scholar: "البخاري" },
    { text: "المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف، وفي كل خير...", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "رضا الرب في رضا الوالد، وسخط الرب في سخط الوالد", book: "جامع الترمذي", grade: "صحيح", narrator: "عبد الله بن عمرو", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "تهادوا تحابوا", book: "الأدب المفرد", grade: "حسن", narrator: "أبو هريرة", bookKey: "other", scholar: "ابن حجر" },
    { text: "صنائع المعروف تقي مصارع السوء", book: "المستدرك على الصحيحين", grade: "صحيح", narrator: "أنس بن مالك", bookKey: "other", scholar: "الألباني" },
    { text: "الظلم ظلمات يوم القيامة", book: "صحيح البخاري", grade: "صحيح", narrator: "عبد الله بن عمر", bookKey: "bukhari", scholar: "البخاري" },
    { text: "من غشنا فليس منا", book: "صحيح مسلم", grade: "صحيح", narrator: "أبو هريرة", bookKey: "muslim", scholar: "مسلم" },
    { text: "آية المنافق ثلاث: إذا حدث كذب، وإذا وعد أخلف، وإذا اؤتمن خان", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "كلكم راع وكلكم مسؤول عن رعيته", book: "صحيح البخاري", grade: "صحيح", narrator: "عبد الله بن عمر", bookKey: "bukhari", scholar: "البخاري" },
    { text: "يد الله مع الجماعة", book: "جامع الترمذي", grade: "صحيح", narrator: "ابن عباس", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "سباب المسلم فسوق، وقتاله كفر", book: "صحيح البخاري", grade: "صحيح", narrator: "عبد الله بن مسعود", bookKey: "bukhari", scholar: "البخاري" },
    { text: "من لا يرحم لا يرحم", book: "صحيح البخاري", grade: "صحيح", narrator: "جریر بن عبد الله", bookKey: "bukhari", scholar: "البخاري" },
    { text: "من كذب علي متعمدا فليتبوأ مقعده من النار", book: "صحيح البخاري", grade: "متواتر", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "المرء مع من أحب", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو موسى الأشعري", bookKey: "bukhari", scholar: "البخاري" },
    { text: "من قام ليلة القدر إيمانا واحتسابا غفر له ما تقدم من ذنبه", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "العمرة إلى العمرة كفارة لما بينهما، والحج المبرور ليس له جزاء إلا الجنة", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "أعطوا الأجير أجره قبل أن يجف عرقه", book: "سنن ابن ماجه", grade: "صحيح", narrator: "عبد الله بن عمر", bookKey: "ibnmajah", scholar: "الألباني" },
    { text: "البياعان بالخيار ما لم يتفرقا", book: "صحيح البخاري", grade: "صحيح", narrator: "حكيم بن حزام", bookKey: "bukhari", scholar: "البخاري" },
    { text: "المكر والخديعة في النار", book: "شعب الإيمان", grade: "صحيح", narrator: "ابن مسعود", bookKey: "other", scholar: "الألباني" },
    { text: "يا غلام سم الله وكل بيمينك وكل مما يليك", book: "صحيح البخاري", grade: "صحيح", narrator: "عمر بن أبي سلمة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "حق المسلم على المسلم خمس: رد السلام، وعيادة المريض، واتباع الجنائز، وإجابة الدعوة، وتشميت العاطس", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "الكلمة الطيبة صدقة", book: "صحيح البخاري", grade: "صحيح", narrator: "أبو هريرة", bookKey: "bukhari", scholar: "البخاري" },
    { text: "لا يموتن أحدكم إلا وهو يحسن الظن بالله", book: "صحيح مسلم", grade: "صحيح", narrator: "جابر بن عبد الله", bookKey: "muslim", scholar: "مسلم" },
    { text: "إن قوما من أمتي سيخرجون فيموتون بغير أرضهم، فأولئك هم الشهداء", book: "رواه الطبراني", grade: "ضعيف", narrator: "أبو أمامة", bookKey: "other", scholar: "ابن الجوزي" },
    { text: "صوموا تصحوا", book: "المعجم الأوسط", grade: "ضعيف", narrator: "أبو هريرة", bookKey: "other", scholar: "الألباني" },
    { text: "اختلاف أمتي رحمة", book: "المقاصد الحسنة", grade: "لا أصل له (موضوع)", narrator: "—", bookKey: "other", scholar: "السخاوي" },
    { text: "النظافة من الإيمان", book: "كشف الخفاء", grade: "ضعيف جداً", narrator: "—", bookKey: "other", scholar: "العجلوني" },
    { text: "خير الأسماء ما عبد وحمد", book: "الضعفاء", grade: "ضعيف", narrator: "—", bookKey: "other", scholar: "العقيلي" },
    { text: "الأقربون أولى بالمعروف", book: "ليس بحديث، إنما هو قاعدة مستنبطة", grade: "لا أصل له كحديث", narrator: "—", bookKey: "other", scholar: "ابن باز" },
    { text: "من عرف نفسه فقد عرف ربه", book: "كشف الخفاء", grade: "لا أصل له (موضوع)", narrator: "—", bookKey: "other", scholar: "ابن تيمية" },
    { text: "لو تعلق قلب أحدكم بالثريا لنالها", book: "الأسرار المرفوعة", grade: "حديث ضعيف", narrator: "—", bookKey: "other", scholar: "القاري" },
    { text: "الدعاء مخ العبادة", book: "جامع الترمذي", grade: "ضعيف", narrator: "أنس بن مالك", bookKey: "tirmidhi", scholar: "الألباني" },
    { text: "رجَعْنا منَ الجِهادِ الأصغرِ إلى الجِهادِ الأكبَرِ", book: "تاريخ بغداد", grade: "ضعيف جداً", narrator: "جابر", bookKey: "other", scholar: "ابن حجر" }
];

